### ISSUE TITLE
Top 7 Questions - Sowden Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#103]
- [x] Ensure Base email template is complete #100 
- [x] Ensure manual email campaign is complete #101 
- [x] Create Automation based on manual email campaign
- [x] Insert Content
   - [x] Insert introduction (There are good builders, great builders...)
   - [x] Insert Questions
      - [x] What are their real qualifications?
      - [x] Who really Supervises your project?
      - [x] What's actually included in the quote?
      - [x] Do they provide written specifications?
      - [x] Are they financially stable?
      - [x] Does your builder have a focus on sustainability
      - [x] Does your builder offer Hempcrete?
- [ ] Create individual emails for each question
   - [x] What are their real qualifications?
      - [x] Answer
   - [x] Who really Supervises your project?
      - [x] Answer
   - [x] What's actually included in the quote?
      - [x] Answer
   - [x] Do they provide written specifications?
      - [x] Answer
   - [x] Are they financially stable?
      - [x] Answer
   - [x] Is your builder focused on sustainability?
      - [x] Answer
   - [x] Does your builder offer hempcrete?
      - [x] Answer
  - [x] Can you work with them?

**Comment by LiamAssetBuilders** [comment]
@ElliottAssetBuilders 
All Questions have been answered

Please review emails before sending copies of each email for Nick.

**Comment by ElliottAssetBuilders** [comment]
I've gone over them, they all look good
