### ISSUE TITLE
=EBROCHURE= Precision Inspections

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#112]
=EBROCHURE=
- [ ] Ensure base template is completed #6 
- [ ] Ensure Base email campaign is completed #7  
- [ ] Create new automation based on email Campaign
- [ ] Insert Content
   - [ ] Introduction Copy
   - [ ] Client Testimonials
   - [ ] Awards
   - [ ] Industry Associations
   - [ ] Insert Photos
- [ ] Duplicate Completed eBrochure for Top 7 Questions Subscribers

**Comment by ElliottAssetBuilders** [comment]
As per discussion in the office today, there is no current identified need for Precision to have an eBrochure.
