### ISSUE TITLE
=TOP 7 Q= Precision Inspections

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#113]
=TOP 7 Qs=
- [x] Ensure Base email template is complete #6 
- [x] Ensure manual email campaign is complete #7 
- [x] Create Automation based on manual email campaign
- [x] Insert Content
   - [x] Insert introduction (There are good builders, great builders...)
   - [x] Insert Questions
      - [x] What are their real qualifications?
      - [x] Who really Supervises your project?
      - [x] What's actually included in the quote?
      - [x] Do they provide written specifications?
      - [x] Are they financially stable?
      - [ ] Are they part of a buying group?
      - [x] Do they have an online client portal?
- [x] Create individual emails for each question
   - [x] What are their real qualifications?
      - [x] Answer
   - [x] Who really Supervises your project?
      - [x] Answer
   - [x] What's actually included in the quote?
      - [x] Answer
   - [x] Do they provide written specifications?
      - [x] Answer
   - [x] Are they financially stable?
      - [x] Answer
   - [x] Are they part of a buying group?
      - [ ] Answer
   - [x] Do they have an online client portal?
      - [x] Answer
  - [x] Can you work with them?

**Comment by ElliottAssetBuilders** [comment]
Top 7 questions have been completed and all emails have been viewed and approved by the client.
