### ISSUE TITLE
=BOOK A MEETING/REQUEST A QUOTE= Precision Inspections

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#115]
=BOOK A MEETING/REQUEST A QUOTE=
- [x] Base email template is complete #6 
- [x] Qualify Questionnaire Complete #12 
- [x] Create new email based on Base Template
- [x] Insert content
   - [x] Introduction (Thank client & Invite them to complete pre-appointment questionnaire)
   - [x] Copy introduction from eBrochure 
   - [x]  Button link to Qualifying Questionnaire
- [x] Duplicate Book a Meeting for Request a Quote

**Comment by LiamAssetBuilders** [comment]
Request a Quote and Book a Meeting Emails have been updated to follow new style

Book a Meeting[[Source](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/EB6DCA76DEBEF819/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.1387351332.1467683271.1467683271.1467683271.1&__utmb=65791729.0.10.1467683271&__utmc=65791729&__utmx=-&__utmz=65791729.1467683271.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=245699395&_ga=1.181118631.1885584307.1445470851)]


Request a Quote[[Source](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/38D2370248D7E14E/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.257304844.1467683301.1467683301.1467683301.1&__utmb=65791729.0.10.1467683301&__utmc=65791729&__utmx=-&__utmz=65791729.1467683301.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=18493566&_ga=1.181135783.1885584307.1445470851)]
