### ISSUE TITLE
TUMBLR - CBS

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#213]
- [x] Get Email & Password
- [x] Check Account is Properly Registered
- [x] Format Page
   - [x] Insert Banner Image
   - [x] Insert Profile Image
   - [x] Insert Facebook 'Like' Button [x](https://developers.facebook.com/docs/plugins/like-button)
   - [x] Insert Title
   - [x] Insert Tagline
   - [x] Insert Description
   - [x] Insert Links (Photo Gallery, Request a Quote, Book a Meeting, Top 7 Questions, eBrochure)

**Comment by LiamAssetBuilders** [comment]
@tksvendsen Password no longer works

**Comment by LiamAssetBuilders** [comment]
Called Stuart - Decided to reset the password, He said he would send me the updated password once the password-reset email had come through

**Comment by LiamAssetBuilders** [comment]
Password has been changed and reaquired

**Comment by tksvendsen** [comment]
Hi Liam, 
I'm taking myself off this,  re assign me if you run into any problems before final handover 
thanks

**Comment by LiamAssetBuilders** [comment]
Tumblr has been set up
