### ISSUE TITLE
FACEBOOK - CBS

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#215]
- [x] Receive Admin Rights
- [x] Remove Rich Training
   - [x] Sign up form button
   - [x] Sign up link (On Cover Photo)
   - [x] Unlike Rich Training Facebook Page
- [x] Branding 
   - [x] Check Description/ About Pages
   - [x] Like Asset Builders Facebook Pages
   - [x] Like Project Portal Facebook Pages
- [x] Links
   - [x] Insert Link to Sign up form
   - [x] Link Call to action to Photo Gallery

**Comment by ElliottAssetBuilders** [comment]
There is a second Facebook Page setup with Rich, will need to get access to the page and delete it

**Comment by ElliottAssetBuilders** [comment]
I've emailed Stuart about getting the second page deleted and also asked for his email address for his profile so we can add him as an admin
