### ISSUE TITLE
TUMBLR - A Class Constructions

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#228]
- [x] Get Email & Password
- [x] Check Account is Properly Registered
- [x] Format Page
   - [x] Insert Banner Image
   - [x] Insert Profile Image
   - [x] Insert Facebook 'Like' Button [x](https://developers.facebook.com/docs/plugins/like-button)
   - [x] Insert Title
   - [x] Insert Tagline
   - [x] Insert Description
   - [x] Insert Links (Photo Gallery, Request a Quote, Book a Meeting, Top 7 Questions, eBrochure)

**Comment by LiamAssetBuilders** [comment]
Tumblr page Styled and copy complete

Last post was made within the past 11 hours

**Comment by patassetbuilders** [comment]
Ok checked, and ready for production
