### ISSUE TITLE
ENEWSLETTER - A Class Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#229]
- [x] Create Base template
- [x] Link Facebook
- [x] Download template
   - [x] Insert Tagline
   - [x] Insert Links
   - [x] Format Colours
   - [x] Insert Footer text ('Powered by Agility Project Portal')
   - [x] Insert Footer Image ('Asset Builders Member')
- [x] Upload and check hardcoded Template
- [x] Add password

**Comment by patassetbuilders** [comment]
Liam to import contacts
