### ISSUE TITLE
EBROCHURE - A Class Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#233]
- [x] Ensure base template is completed #231  
- [x] Ensure Base email campaign is completed #232   
- [x] Create new automation based on email Campaign
- [x] Insert Content
   - [x] Introduction Copy
   - [x] Client Testimonials
   - [x] Awards
   - [x] Industry Associations
   - [x] Insert Photos
- [x] Duplicate Completed eBrochure for Top 7 Questions Subscribers

**Comment by ElliottAssetBuilders** [comment]
Hey Liam I've completed the eBrochure, can you please do the quality assurance check on it and if there are no issues close it off.

**Comment by LiamAssetBuilders** [comment]
@ElliottAssetBuilders 

I feel like there are too many full stops and short sentences in the introduction - and a bit too much fluff like 'we create building projects that meet our client's needs' which just feels really insubstantial. (and it also feels like it was kinda dropped in there. the sentence reads much better without it). It makes reading it really jarring. 

Might also want to give the buttons a second pass. The text overlapping with the 'a' feels a bit too busy (and I think we need to figure out a better way to present buttons, regardless)

I also thought the '10 reasons why we are the best choice for your project' was going to be our top 7 questions email. As it is now in the eBrochure. it looks kinda cramped.

Finally. I feel like some of the sections and cells would look better if they were closer together (I'll do that now)

But the Colours and layout look great.

**Comment by LiamAssetBuilders** [comment]
- [ ] Remember to add company contact details and invite the reader to share the email with their friends

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders Updated the eBrochure to be more inline with the style of the other emails
[[Preview Here](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/844698B0B3E22193/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.891720147.1466128985.1466128985.1466128985.1&__utmb=65791729.0.10.1466128985&__utmc=65791729&__utmx=-&__utmz=65791729.1466128985.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=249814209&_ga=1.189525291.1885584307.1445470851)]

Sent a copy to Scott Last night, but have yet to get a reply.

**Comment by patassetbuilders** [comment]
reviewed and closed
