### ISSUE TITLE
10 Questions you should ask your builder - A Class Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#234]
- [x] Ensure Base email template is complete #231  
- [x] Ensure manual email campaign is complete #232  
- [x] Create Automation based on manual email campaign
- [x] Insert Content
   - [x] Insert introduction (There are good builders, great builders...)
   - [x] Insert Questions
- [x] Create individual emails for each question

1. We offer full contract, project management or labour-only contracts so you can choose which contract option works best for you.
2. Each project receives our personal attention so your project is completed to the highest possible standards.
3. All our tradesmen are trustworthy, reliable & have been handpicked by us for their expertise & workmanship.
4. All our products & materials are of high quality & meet all relevant standards.
5. We are registered with the Master Builders Association of Australia, which helps us keep up to date with any changes in our industry.
6. We take pride in ourselves for being honest & always having good communication throughout the duration of your project so you always know where you stand with us.
7. You are always welcome to ring us, visit the site or arrange extra meetings at any time.
8. You will be 100% satisfied with your home and our service.
9. For your peace of mind, we have 35 years of combined industry knowledge and experience in the local Illawarra area.
10. We know how important it is to complete your home on budget. With our experience in the building industry, all costs are accurate, even down to the smallest detail. Any changes you choose to make that incur extra cost will be explained in detail so you can make an informed decision.

**Comment by ElliottAssetBuilders** [comment]
Going to need help with the copy on this

**Comment by LiamAssetBuilders** [comment]
We have reposed this as 10 Questions you should ask your builder.

- [ ] How experienced is your builder
   - [ ] Content
- [ ] Will your project be finished on time and on budget?
   - [ ] Content
- [ ] How flexible is your builder?
   - [ ] Content
- [ ] Does your project receive personal attention?
   - [ ] Content
- [ ] How professional are their tradespeople and sub contractors?
   - [ ] Content
- [ ] Does your builder use only top rated suppliers and materials?
   - [ ] Content
- [ ] Are they active participants in industry associations?
   - [ ] Content
- [ ] Does your builder go out of their way to keep you informed?
   - [ ] Content
- [ ] Does your builder offer a satisfaction guarantee?
   - [ ] Content
- [ ] Is your builder customer focused?
   - [ ] Content

**Comment by LiamAssetBuilders** [comment]
Top 10 Questions is now Content complete

@patassetbuilders Passing it over to you for a final check before we send them to Scott for approval.

**Comment by patassetbuilders** [comment]
closed all emails sent
