### ISSUE TITLE
QUALIFY QUESTIONNAIRE - A Class Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#235]
- [x] Duplicate Master copy of Qualify Questionnaire
- [x] Format Qualify Questionnaire
   - [x] Replace Contact Information
   - [x] Insert additional Questions (If Applicable)
   - [x] Create Thank you emails
   - [x] Create notification emails
   - [x] Link Photo Gallery as landing page
- [ ] Email client with preview'

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders No copy emailed to Scott yet.

**Comment by patassetbuilders** [comment]
Ok fixed a couple of spelling mistakes, I will email to scott. 
@LiamAssetBuilders
