### ISSUE TITLE
BOOK A MEETING/REQUEST A QUOTE - A Class Building

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#236]
- [x] Base email template is complete #231  
- [x] Qualify Questionnaire Complete #235  
- [x] Create new email based on Base Template
- [x] Insert content
   - [x] Introduction (Thank client & Invite them to complete pre-appointment questionnaire)
   - [x] Copy introduction from eBrochure 
   - [x]  Button link to Qualifying Questionnaire
- [x] Duplicate Book a Meeting for Request a Quote

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders For confirmation

[[Source](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/A8AB2A54EA0FD5F3/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.384273505.1466396504.1466396504.1466396504.1&__utmb=65791729.0.10.1466396504&__utmc=65791729&__utmx=-&__utmz=65791729.1466396504.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=43120482&_ga=1.143902005.1885584307.1445470851)]

**Comment by patassetbuilders** [comment]
Reviewed and closed
