### ISSUE TITLE
Challenging - Need Payment details

### ISSUE THREAD

**Issue by Deeds69** [patassetbuilders/social-media-#260]
I have been unable to get payment details from Stuart. Tyrone to contact Stuart.

**Comment by patassetbuilders** [comment]
Hi Tyrone,

We don't have Chris contacts so although the eNewsletter is complete, no joy with this item.
Deeds has attempted to contact Chris many times without success, thats why this task is assigned to you.
Regards,
Pat

**Comment by Deeds69** [comment]
Have bank account details now will start charging from 1st September 2016
