### ISSUE TITLE
=TOP 7 Qs= I live constructions

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#275]
- [x] Ensure Base email template is complete #6 
- [x] Create Automation based on manual email campaign
- [x] Insert Content
   - [x] Insert introduction (There are good builders, great builders...)
   - [x] Insert Questions
      - [x] What are their real qualifications?
      - [x] Who really Supervises your project?
      - [x] What's actually included in the quote?
      - [x] Do they provide written specifications?
      - [x] Are they financially stable?
      - [x] Are they open to using innovative technology?
      - [x] Is your builder transparent?
- [x] Create individual emails for each question
   - [x] What are their real qualifications?
      - [x] Answer
      - [ ] Email to client as completed
   - [x] Who really Supervises your project?
      - [x] Answer
      - [ ] Email to client as completed
   - [x] What's actually included in the quote?
      - [x] Answer
      - [ ] Email to client as completed
   - [x] Do they provide written specifications?
      - [x] Answer
      - [ ] Email to client as completed
   - [x] Are they financially stable?
      - [x] Answer
      - [ ] Email to client as completed
   - [x] Are they part of a buying group?
      - [x] Answer
      - [ ] Email to client as completed
   - [x] Do they have an online client portal?
      - [x] Answer
      - [ ] Email to client as completed
  - [x] Can you work with them?
  - [ ] Email to client as completed

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 

First Top 7 Questions Email Complete
[[Source](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/149E86B0FF1F7B6D/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.156177792.1466654640.1466654640.1466654640.1&__utmb=65791729.0.10.1466654640&__utmc=65791729&__utmx=-&__utmz=65791729.1466654640.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=248765632&_ga=1.220897560.1885584307.1445470851)]

They have a few custom questions, I would appreciate your help with the copy on those.
-Thanks

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 

First draft for answers have been added to individual Top 7 Questions emails.
if we could go over the copy, I would really appreciate it.
