### ISSUE TITLE
=MANUAL EMAIL CAMPAIGN=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#276]
Set up manual email campaign

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 
Manual Email Campaign is complete
[[Source](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/229964CD482F311D/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.474775646.1466562041.1466562041.1466562041.1&__utmb=65791729.0.10.1466562041&__utmc=65791729&__utmx=-&__utmz=65791729.1466562041.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=253489358&_ga=1.160146877.1885584307.1445470851)]

May need a group photo to replace the iLiv Group logo, however.

**Comment by patassetbuilders** [comment]
Hi @LiamAssetBuilders 

The qualify questionnaire link is not correct
http://www.project-portal.com.au/pages/4434/Qualify_Questionnaire
should be lower case  qualify_questionnaire

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 
Thank you for bringing this to my attention. Link has been fixed, you can confirm through the previous link.
