### ISSUE TITLE
=EBROCHURE=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#277]
=EBROCHURE=
- [x] Ensure base template is completed #6 
- [x] Ensure Base email campaign is completed #7  
- [x] Create new automation based on email Campaign
- [x] Insert Content
   - [x] Introduction Copy
   - [x] Client Testimonials
   - [x] Awards
   - [x] Industry Associations
   - [x] Insert Photos
   - [x] set up social media links
- [ ] Duplicate Completed eBrochure for Top 7 Questions Subscribers

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 
First draft of eBrochure is complete
[[Source](http://assetbuildersagilityprojectportal.createsend.com/t/ViewEmail/t/BA49BE4E3D499219/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1&__utma=65791729.819462897.1466649391.1466649391.1466649391.1&__utmb=65791729.0.10.1466649391&__utmc=65791729&__utmx=-&__utmz=65791729.1466649391.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)&__utmv=-&__utmk=254073039&_ga=1.250251782.1885584307.1445470851)]

Should have a session running over the copy some time soon.

**Comment by patassetbuilders** [comment]
Need headshot
