### ISSUE TITLE
=EMAIL CAMPAIGN=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#278]
=EMAIL CAMPAIGN=
- [x] Ensure base email template complete #6 
- [x] Create Campaign from base email template
- [x] Set Up basic Format
   - [x] Insert introduction
      - [x] Use Photo of Client
	- [x] Insert Buttons (request a quote, Book a Meeting, View Photo Gallery)
        - [x] Ensure manual email campaign is complete #7    
        - [x] Insert farewell

**Comment by LiamAssetBuilders** [comment]
This is a duplicate See other eMail Campaign Issue
