### ISSUE TITLE
=EMAIL TEMPLATE=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#279]
- [x] Insert Client Logo or Company Title
- [x] Insert Link bar
   - [x] Request a Quote
   - [x] Book a Meeting
   - [x] View Photo Gallery
- [x] Insert Footer
   - [x] Address
   - [x] Phone
   - [x] Email
   - [x] Asset Member Logo
- [x] Link Social Media (Facebook,Instagram, Website and Others where applicable)
- [x] Create Format
   - [x] Select Background Colour
   - [x] Select Header Font & Colour
   - [x] Select Text Font & Colour
   - [x] Select Link Colour
   - [x] Select Button Colour

**Comment by LiamAssetBuilders** [comment]
Check the Manual Email Campaign for results
