### ISSUE TITLE
=FACEBOOK=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#280]
- [x] Receive Admin Rights
- [x] Remove Rich Training
   - [x] Sign up form button
   - [x] Sign up link (On Cover Photo)
   - [x] Unlike Rich Training Facebook Page
- [x] Branding 
   - [x] Check Description/ About Pages
   - [x] Like Asset Builders Facebook Pages
   - [x] Like Project Portal Facebook Pages
- [x] Links
   - [x] Insert Link to Sign up form
   - [x] Link Call to action to Photo Gallery

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 
iLiv Facebook page has been correctly set up and linked to Instagram

Venessa & Rachel Downham have both been very active posters on FB
[[Source](https://www.facebook.com/ILiv-Constructions-1574875002809843/)]
