### ISSUE TITLE
=QUALIFY QUESTIONNAIRE=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#281]
- [x] Duplicate Master copy of Qualify Questionnaire
- [x] Format Qualify Questionnaire
- [x] Replace Contact Information
- [x] Insert additional Questions (If Applicable)
- [x] Create Thank you emails
- [x] Create notification emails
- [x] Link Photo Gallery as landing page
- [ ] Email client with preview'

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders 
iLiv Constructions qualify questionnaire complete

[[source](https://form.jotform.com/61741367540960)]
