### ISSUE TITLE
=ENEWSLETTER=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#283]
- [x] Create Base template
- [x] Link Facebook
- [x] Download template
   - [x] Insert Tagline
   - [x] Insert Links
   - [x] Format Colours
   - [x] Insert Footer text ('Powered by Agility Project Portal')
   - [x] Insert Footer Image ('Asset Builders Member')
- [x] Upload and check hardcoded Template
- [x] Add password
- [x] Forward eNewsletter operational email to client ccDeeds and Business Manager

**Comment by LiamAssetBuilders** [comment]
@patassetbuilders eNewsletter for iLivConstructions (Downham Developers) Is complete

Here is a copy of their eNewsletter [[Source](http://assetbuilders.projectportal.com.au/t/ViewEmail/t/98A7F5EC42169857)]

**Comment by patassetbuilders** [comment]
Complete, Liam to change photo gallery to portfolio

**Comment by patassetbuilders** [comment]
email sent to iive constructions
