### ISSUE TITLE
=TUMBLR=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#284]
=TUMBLR=
- [x] Get Email & Password
- [x] Check Account is Properly Registered
- [x] Format Page
   - [x] Insert Banner Image
   - [x] Insert Profile Image
   - [x] Insert Facebook 'Like' Button [x](https://developers.facebook.com/docs/plugins/like-button)
   - [x] Insert Title
   - [x] Insert Tagline
   - [x] Insert Description
   - [x] Insert Links (Photo Gallery, Request a Quote, Book a Meeting, Top 7 Questions, eBrochure)

**Comment by LiamAssetBuilders** [comment]
Signed off by @daleasset 

[[Source](http://ilivconstructions.tumblr.com/)]
