### ISSUE TITLE
=SIGN UP FORMS=

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#285]
=SIGN UP FORMS=
- [x] Create External Sign up Forms (Link to sign up page)
   - [x] Insert Client logo or Company name
   - [x] Insert Appropriate custom fields
   - [x] Format Colour and Font

- [x] Create Internal Sign up Form (Add code to your website)
   - [x] Copy Code to coding software
   - [x] Format with Twitter Bootstrap

**Comment by LiamAssetBuilders** [comment]
Signed off by @daleasset
