### ISSUE TITLE
Chasing Payment Details for monthly invoice

### ISSUE THREAD

**Issue by Deeds69** [patassetbuilders/social-media-#289]
Need credit card or bank account details and amount to invoice monthly
Credit Card - Need Card Number, Expiry Date & CCV (Security Number)
Direct Debit - Need Bank Account Number, BSB number, Account Name
**The monthly digital marketing charge will commence 30 days from final handover or on the 1st of the following month**.

**Comment by daleasset** [comment]
Meeting on 23.06.16 to get contacts list and payment details.

**Comment by daleasset** [comment]
Deed to follow up - she has sent through the CC form for details to put in stripe / direct debit?? Will leave open until details are confirmed in the system...

**Comment by Deeds69** [comment]
Rachel returned their payment details form.
Has been Set up in Xero as a recurring monthly transaction, First payment will commence on 1st August 2016.
