### ISSUE TITLE
Create simple website

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#297]
Hi Liam see me re this

**Comment by LiamAssetBuilders** [comment]
Set up and passing on to @patassetbuilders for final setup

**Comment by patassetbuilders** [comment]
website is live but need to confirm if the client actually owns the domain name.
http://home-extensions-eastern-suburbs-sydney.street-directory.com.au/

**Comment by patassetbuilders** [comment]
Good feedback from IBW - billing followup through Xero accounting system
