### ISSUE TITLE
=MANUAL eNEWSLETTER=  - [ ] create and send to client

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#298]
This is still outstanding

**Comment by ElliottAssetBuilders** [comment]
I've setup the manual newsletter for IBW @LiamAssetBuilders could you please conduct a quality control check on my work for me to ensure I haven't missed anything.

**Comment by LiamAssetBuilders** [comment]
@ElliottAssetBuilders the Manual eNewsletter for IBW has been set up correctly - everything looks fine
