### ISSUE TITLE
need contacts 

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#302]
only three contacts present

**Comment by daleasset** [comment]
Have emailed Barry, requesting the email lists, will organise to get down to see them next week along with Hollyman homes and iLiv Constructions.

**Comment by daleasset** [comment]
Meeting on Thursday 23.06.16 to organise contacts

**Comment by daleasset** [comment]
List obtained 23.06.16 from Barry @ Allwood
