### ISSUE TITLE
=Final Hand Over= by Business manager

### ISSUE THREAD

**Issue by ElliottAssetBuilders** [patassetbuilders/social-media-#327]
=Final Hand Over= by Business manager
 - [x] Subscribe form
 - [x] Remove any unwanted contacts
 - [x] Check that the user knows how to edit their contacts Note need to log in through the project portal.
 - [x] Instragtam posts 
 - [x] How to send a manual email campaign
 - [x] Semd manual eNewsletter
 - [x] Manually send an autoresponder
 - [x] issue final invoice is no problems. assign  to deeds
 - [x] newsletter is going out to the right number of contacts.

**Comment by patassetbuilders** [comment]
Hi Tyrone,
They are back, you should complete the final hand over asap

**Comment by tksvendsen** [comment]
Closed and done
