### ISSUE TITLE
Add asset contacts

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#329]
Note there are a couple of segments,
Current, Prospect, Lost
for lost, I would look at anyone that has not used them in say the last six months.

**Comment by Deeds69** [comment]
I have emailed a csv file of Cukuna contacts - current and lost to Liam.
Do I also create and send to Liam a csv file of all other NSW members as Prospects for Cukuna ?

**Comment by LiamAssetBuilders** [comment]
Imported Cekuna's contact list and updated segments.
