### ISSUE TITLE
Update facebook links in auto responders 

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#349]
- [x] Update facebook links

- [x] question 3 email

- [x] question 4

- [x] question 5

- [x] question 6

- [x] question 7 

- [x] question 8 

- [x] swap question 8 for six

- [x] can you work with them, I given 

- [x] copy of enews 
- [x] letter
- [x] other manual email campaign
- [x] like us on facebook

**Comment by LiamAssetBuilders** [comment]
All Emails have been updated with the new address
