### ISSUE TITLE
Final Hand over

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#352]
Hi Tyrone,
This will be ready for final hand over by the end of the week.
I have turned the on the enewsletter  there are alot a good posts and contacts.

**Comment by ElliottAssetBuilders** [comment]
We're ready for handover

**Comment by tksvendsen** [comment]
1. So Nick tells me he was getting around 4 inquiries via his website each week, pre changing it over to our pre appointment questionnaire.   He thinks obviously people are just not getting through it.   

Is there a way the first page can capture the information in case they don't finish the WHOLE application.   

I showed him how we could do it via email, similar to our sign up forms.    He said that could work, though would rather something like our strategic review where it's a double capture to begin with.   

2.  He also asked about metrics of how many people get to things like his photo gallery
