### ISSUE TITLE
Update emails with the new logo

### ISSUE THREAD

**Issue by ElliottAssetBuilders** [patassetbuilders/social-media-#357]
Ensure once the updated logo is complete that the emails and Facebook are updated with the new logo

**Comment by LiamAssetBuilders** [comment]
@ElliottAssetBuilders 

Called and Emailed Abey about his logo, and several versions I have made of it for his approval.
Said he would get back to me later in the afternoon.

**Comment by LiamAssetBuilders** [comment]
Logos are awaiting approval.

**Comment by LiamAssetBuilders** [comment]
Logos and Colour Scheme have been approved for use.

**Comment by LiamAssetBuilders** [comment]
@ElliottAssetBuilders New Logos have been added to all of Duke Projects' Auto Resonders, Campaigns, eNewsletter, sign up forms, portfolio and Facebook

Need to reobtain access to tumblr to change
