### ISSUE TITLE
Articles - Quality Controll - Duke Projects

### ISSUE THREAD

**Issue by LiamAssetBuilders** [patassetbuilders/social-media-#381]
All Articles - except eBrochure are complete, please review and forward to Abey.

- [x] eNewsletter
- [x] eBrochure
- [x] Book a Meeting/Request a Quote
- [x] Top 8 Questions
- [x] Q1
- [x] Q2
- [x] Q3
- [x] Q4
- [x] Q5
- [x] Q6
- [x] Q7
- [x] Q8
- [x] Q9
- [x] Email Campaigns
- [x] Find us on Facebook

**Comment by ElliottAssetBuilders** [comment]
Quality control completed and emails have been sent to the client for approval
