### ISSUE TITLE
Facebook - Duke

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#50]
Next issue https://github.com/patassetbuilders/social-media-/issues/51

- [x] Receive Admin Rights
- [x] Remove Rich Training
   - [x] Sign up form button
   - [x] Sign up link (On Cover Photo)
   - [x] Unlike Rich Training Facebook Page
- [x] Branding 
   - [x] Check Description/ About Pages
   - [x] Like Asset Builders Facebook Pages
   - [x] Like Project Portal Facebook Pages
- [x] Links
   - [x] Insert Link to Sign up form
   - [x] Link Call to action to Photo Gallery

**Comment by LiamAssetBuilders** [comment]
Facebook has been updated to fit with new style
